### ISSUE TITLE
Explicit katip support is unnecessary

### ISSUE THREAD

**Issue by parsonsmatt** [lykahb/ory-hydra-client#2]
I should write a more thorough blog post on this... but it's unnecessary to support switching the log library based on a cabal flag. By choosing to depend on one library or the other through a common module signature, you're restricting yourself to the least powerful interface - in this case, `monad-logger`. It is relatively straightforward to write a `MonadLogger` instance that delegates to `katip`'s methods.

I'd suggest simplifying the library by only requiring `monad-logger` and allowing end-users to pick how they want to instantiate that class.

**Comment by lykahb** [comment]
@parsonsmatt Yeah, the structure of this library could be more flexible. However, this is automatically generated code, with only a few edits to readme. So, this issue would be more fitting for https://github.com/OpenAPITools/openapi-generator. It has two haskell generators. The one ory-hydra-client uses is [here](https://github.com/OpenAPITools/openapi-generator/tree/master/modules/openapi-generator/src/main/resources/haskell-http-client).
